image: Visual Studio 2017
version: 1.2.0-{build}
services:
  - postgresql
environment:
  global:
    DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
    DOTNET_CLI_TELEMETRY_OPTOUT: 1
    NPGSQL_TEST_DB: Host=localhost;Database=postgres;Username=postgres;Password=Password12!
cache:
  - '%USERPROFILE%\.nuget\packages -> **\*.csproj'
shallow_clone: true
install:
  - ps: $env:padded_build_number = $env:appveyor_build_number.PadLeft(5, '0')
before_build:
  - appveyor-retry dotnet restore -v Minimal
build_script:
  - msbuild /p:Configuration=Debug
  - msbuild /p:Configuration=Release
  - dotnet pack src\Npgsql.EntityFrameworkCore.PostgreSQL\Npgsql.EntityFrameworkCore.PostgreSQL.csproj -c Release --version-suffix ci-%PADDED_BUILD_NUMBER%
  - dotnet pack src\Npgsql.EntityFrameworkCore.PostgreSQL.Design\Npgsql.EntityFrameworkCore.PostgreSQL.Design.csproj -c Release --version-suffix ci-%PADDED_BUILD_NUMBER%
artifacts:
  - path: 'src\Npgsql.EntityFrameworkCore.PostgreSQL\bin\**\*.nupkg'
  - path: 'src\Npgsql.EntityFrameworkCore.PostgreSQL.Design\bin\**\*.nupkg'
deploy:
  - provider: NuGet
    server: https://www.myget.org/F/npgsql-unstable/api/v2/package
    api_key:
      secure: kiMn9uBvgMa5EtEmTIhNBFUfyatiATnhkgx5Xj/1EsmKTtEkUv+hJAQs0L3VGzPw
    artifact: /.*\.nupkg/
    skip_symbols: true
    #skip_symbols: false
    #symbol_server: https://your.symbol.server/feed

